[app]
name="courses"
version="1.0.0"
port="5000"
host="127.0.0.1"

[db]
engine="postgres"
host="localhost"
port="5432"
name="courses"
user="postgres"
password="postgres"

[logger]
debug-mode=true
format="%{color}%{time:2006/01/02 15:04:05 -07:00 MST} [%{level:.6s}] %{shortfile} : %{color:reset}%{message}"

[token-signing]
secret="Iamasecretbutnottheusualyouexpectlol"
expiration=30
